### ISSUE TITLE
having issues with H1 bottom margin and the spacing outside the cards on small screens and the spacing between on large screens.

### ISSUE THREAD

**Issue by sent0007** [sent0007/lists-n-grids#1]
@mackenzierose

Hi Mackenzie,

I'm having issues with the H1 bottom margin. It seems to be in between push 1 and push-1-2 or a combination of other spacing classes that I can't figure out how to align with markbot. Also having issues with the spacing around the cards and between on larger screens. Any ideas or guidance would be greatly appreciated. 

Thanks, Curtis. 

https://github.com/sent0007/lists-n-grids/blob/bec9eb197b671b7f2713a6591f64e14225b8f7e2/index.html#L14

https://github.com/sent0007/lists-n-grids/blob/bec9eb197b671b7f2713a6591f64e14225b8f7e2/index.html#L13

**Comment by MacKenzieRose** [comment]
Hi Curtis,

It looks like your files are passing Markbot's screenshots, which is dope.

If you wanted to get things a little closer to perfect for the screenshots, there are a couple of other things you can do:

1) In your list elements, your island class is competing with your bottom padding. To avoid this, use gutter-1-4, pad-t-1-4, and leave pad-b as is.

2) Your paragraph elements have too much margin, so adjusting your push value will fix that.

3) Your h1 needs some gutter to pull it away from the edge of the page. 

4) And then finally, to fix the space after your h1, add some padding to the top of your grid/ol.

Cheers!

MacKenzie

**Comment by sent0007** [comment]
Okay perfect thanks for the direction !
